name: Scala CI

env:
  IMAGE_NAME: github-actions-sbt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
    # sbt-native-packager doesn't support Docker repository authentication, so do a docker push after publish to your local repository.
    # https://www.scala-sbt.org/sbt-native-packager/formats/docker.html#requirements
    - name: Publish Local
      run: sbt docker:publishLocal
    - name: Login GitHub Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u owner --password-stdin
    - name: Push image to GitHub Registry
      run: |
        docker tag ${IMAGE_NAME}:0.0.0 docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${GITHUB_SHA}
        docker push docker.pkg.github.com/${{ github.repository }}/${IMAGE_NAME}:${GITHUB_SHA}
